### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by XuRui314** [OpenGVLab/GUI-Odyssey#2]
目前的仓库的代码并不能直接跑通（例如测试代码 evaluate_GUIOdyssey.py）
我遇到的问题的解决方法：
1. 对于Qwen的`tokenizer_qwen`文件会报错IMAGE_ST相关错误，这个把super().__init__放到IMAGE_ST下面即可
2. 本地加载文件的话，需要在`modeling_qwen`文件的41行替换为下面的
```python
from .configuration_qwen import QWenConfig
from qwen_generation_utils import (
    HistoryType,
    make_context,
    decode_tokens,
    get_stop_words_ids,
    StopWordsLogitsProcessor,
)
from .visual import VisionTransformer
```
3.  对于his_index的构建代码，也就是data目录下的format_converter.py，需要把104行改成test_anno_base，以及168行把data['history']改成data['history_screenshot']

另外就是his_index的建议，建议可以增加一个无history的处理方式比如单图输入的情况，而不是每次都需要his_index，挺麻烦的

**Comment by XuRui314** [comment]
还漏了一个那个模型的generation_config也是要替换成Qwen的才行

**Comment by XuRui314** [comment]
his_index那个问题我的解决方法是增加一个SINGLE_IMAGE变量，然后modeling_qwen文件639行改成：
```python
        if SINGLE_IMAGE:
            self.imgtoken_dict =  {}
        else:
            if os.path.isdir(IMAGE_HISTORY):
                for subdata in os.listdir(IMAGE_HISTORY):
                    sub_img_dict = json.load(open(os.path.join(IMAGE_HISTORY, subdata)))
                    self.imgtoken_dict.update(sub_img_dict)
            else:
                self.imgtoken_dict = json.load(open(IMAGE_HISTORY))

```

**Comment by XuRui314** [comment]
然后就能跑通这个推理了：
```python
from transformers import AutoModelForCausalLM, AutoTokenizer
from transformers.generation import GenerationConfig
import torch
torch.manual_seed(1234)

# Note: The default behavior now has injection attack prevention off.
tokenizer = AutoTokenizer.from_pretrained("/root/data/models/OdysseyAgent-random", trust_remote_code=True)

# use bf16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
# use fp16
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
# use cpu only
# model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cpu", trust_remote_code=True).eval()
# use cuda device
model = AutoModelForCausalLM.from_pretrained("/root/data/models/OdysseyAgent-random", device_map="cuda:2", trust_remote_code=True).eval()

# Specify hyperparameters for generation
model.generation_config = GenerationConfig.from_pretrained("/root/data/models/OdysseyAgent-random", trust_remote_code=True)

# 1st dialogue turn
query = tokenizer.from_list_format([
    {'image': '/root/data/GUI-Odyssey/src/photo_2019-11-01_15-23-11.jpg'}, # Either a local path or an url
    {'text': '这是什么?'},
])
response, history = model.chat(tokenizer, query=query, history=None)
print(response)
```
但是结果输出的是坐标，应该是模型过拟合太严重了

**Comment by Lqf-HFNJU** [comment]
> 目前的仓库的代码并不能直接跑通（例如测试代码 evaluate_GUIOdyssey.py） 我遇到的问题的解决方法：
> 
> 1. 对于Qwen的`tokenizer_qwen`文件会报错IMAGE_ST相关错误，这个把super().__init__放到IMAGE_ST下面即可
> 2. 本地加载文件的话，需要在`modeling_qwen`文件的41行替换为下面的
> 
> ```python
> from .configuration_qwen import QWenConfig
> from qwen_generation_utils import (
>     HistoryType,
>     make_context,
>     decode_tokens,
>     get_stop_words_ids,
>     StopWordsLogitsProcessor,
> )
> from .visual import VisionTransformer
> ```
> 
> 3. 对于his_index的构建代码，也就是data目录下的format_converter.py，需要把104行改成test_anno_base，以及168行把data['history']改成data['history_screenshot']
> 
> 另外就是his_index的建议，建议可以增加一个无history的处理方式比如单图输入的情况，而不是每次都需要his_index，挺麻烦的

感谢您的反馈！我们已经在最新的版本里修复`format_converter.py`中his_index的构建问题。
使用his_index的原因是Qwen-VL的tokenize过程限制文本输入的<img>...</img>内的字符为255个，因此使用索引记录历史图片路径的方式来避免该问题。若仅是用作无历史图片的推理，其实是不需要his_index的。

**Comment by Lqf-HFNJU** [comment]
> 然后就能跑通这个推理了：
> 
> ```python
> from transformers import AutoModelForCausalLM, AutoTokenizer
> from transformers.generation import GenerationConfig
> import torch
> torch.manual_seed(1234)
> 
> # Note: The default behavior now has injection attack prevention off.
> tokenizer = AutoTokenizer.from_pretrained("/root/data/models/OdysseyAgent-random", trust_remote_code=True)
> 
> # use bf16
> # model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, bf16=True).eval()
> # use fp16
> # model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="auto", trust_remote_code=True, fp16=True).eval()
> # use cpu only
> # model = AutoModelForCausalLM.from_pretrained("Qwen/Qwen-VL-Chat", device_map="cpu", trust_remote_code=True).eval()
> # use cuda device
> model = AutoModelForCausalLM.from_pretrained("/root/data/models/OdysseyAgent-random", device_map="cuda:2", trust_remote_code=True).eval()
> 
> # Specify hyperparameters for generation
> model.generation_config = GenerationConfig.from_pretrained("/root/data/models/OdysseyAgent-random", trust_remote_code=True)
> 
> # 1st dialogue turn
> query = tokenizer.from_list_format([
>     {'image': '/root/data/GUI-Odyssey/src/photo_2019-11-01_15-23-11.jpg'}, # Either a local path or an url
>     {'text': '这是什么?'},
> ])
> response, history = model.chat(tokenizer, query=query, history=None)
> print(response)
> ```
> 
> 但是结果输出的是坐标，应该是模型过拟合太严重了

我们仅分别在GUI Odyssey的random/app/task/device的训练集训练一个epoch，没有使用其他通用（对话等）的训练数据。而GUI Odyssey数据集的标注是聚焦在预测下一步的行为（点击、滑动、键入等），并不包含通用理解、对话等数据，因此是有可能使得训练后的模型对话能力出现遗忘的。
我们也推荐您通过我们提供的微调代码使用GUI Odyssey数据集进行尝试，探索更强大的GUI导航助手。

**Comment by XuRui314** [comment]
好的，感谢回复，非常棒的工作👍

**Comment by XuRui314** [comment]
另外麻烦请问对于Cogagent和其他模型的评测脚本可以提供吗，我看仓库还没有代码
