### ISSUE TITLE
请问可以提供training的脚本吗？

### ISSUE THREAD

**Issue by XuRui314** [OpenGVLab/GUI-Odyssey#4]
仓库里似乎只有finetune的脚本，而基于Qwen初始化权重，以及调整可训练参数并没有体现

请问如果我想要复现training的过程，将Qwen的权重加载到Odyssey模型对应位置，并参考论文中的参数冻结设置，这样的流程是否就够了

**Comment by XuRui314** [comment]
另外请问Qwen是选用 Chat 版本还是 base 版本作为初始化

**Comment by Lqf-HFNJU** [comment]
您好，
Qwen是选用 Chat 版本进行初始化的。
OdysseyAgent用Qwen-VL-Chat权重初始化部分可以参见`src/merge_weight.py`,您只需按照`Quickstart.md`里描述的步骤，运行完`merge_weight.py`即可在`/OdysseyAgent`目录下获得用Qwen-VL-Chat初始化后的OdysseyAgent的模型权重。
`finetune.py`就是模型训练的过程，权重冻结设置可以参见其第287-291行。

**Comment by XuRui314** [comment]
收到谢谢
