### ISSUE TITLE
Model checkpoint

### ISSUE THREAD

**Issue by Wloner0809** [OpenGVLab/GUI-Odyssey#6]
Hi there,

Thank you for your wonderful work. Do you have any plans to publish the model ckpt recently?

**Comment by Lqf-HFNJU** [comment]
Hi,
We have released 4 related models at https://huggingface.co/collections/hflqf88888/gui-odyssey-6683bac37ad6fe37b1215c18.

**Comment by Wloner0809** [comment]
> Hi, We have released 4 related models at https://huggingface.co/collections/hflqf88888/gui-odyssey-6683bac37ad6fe37b1215c18.

Thank you very much for your reply
