### ISSUE TITLE
Can't reproduce the result.

### ISSUE THREAD

**Issue by ApolloRay** [OpenGVLab/GUI-Odyssey#8]
`total episode: 1139, successful episode: 38, SR: 3.34
{'AMS': 58.76, 'SR': 3.34, 'total': 17455, 'action_type': '14393 / 17455 = 82.46', 'text': '1125 / 1271 = 88.51'}`
I'm not sure whether there is somethine wrong during the inference. I choose app_split for dataset.

**Comment by Lqf-HFNJU** [comment]
Hi, 
Please verify that the model in use is OdysseyAgent-**app** and not a different one when using app_split.
